# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  load_workspace_cmd:
    steps:
      - attach_workspace:
          at: ~/workspace
  install_cmd:
    steps:
      - run:
          name: Install monorepo dependencies
          command: yarn install
      - run:
          name: Install monorepo/packages dependencies
          command: yarn bootstrap
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - packages/*
            - node_modules/*
            - package.json
            - lerna.json
  release_cmd:
    steps:
      - load_workspace_cmd
      - run:
          name: Contextual release
          command: ./ci/release.sh

executors:
  node-executor:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12-browsers

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - install_cmd
  release:
    executor: node-executor
    steps:
      - checkout
      - release_cmd

workflows:
  build_and_release:
    jobs:
      - install:
          context: npm-auto
      - release:
          context: npm-auto
          requires:
            - install
